// Generated by gencpp from file lab3/GetPlan.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_GETPLAN_H
#define LAB3_MESSAGE_GETPLAN_H

#include <ros/service_traits.h>


#include <lab3/GetPlanRequest.h>
#include <lab3/GetPlanResponse.h>


namespace lab3
{

struct GetPlan
{

typedef GetPlanRequest Request;
typedef GetPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlan
} // namespace lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab3::GetPlan > {
  static const char* value()
  {
    return "44a0aaa090fcf50f2c1cf7a17cc6eb4d";
  }

  static const char* value(const ::lab3::GetPlan&) { return value(); }
};

template<>
struct DataType< ::lab3::GetPlan > {
  static const char* value()
  {
    return "lab3/GetPlan";
  }

  static const char* value(const ::lab3::GetPlan&) { return value(); }
};


// service_traits::MD5Sum< ::lab3::GetPlanRequest> should match 
// service_traits::MD5Sum< ::lab3::GetPlan > 
template<>
struct MD5Sum< ::lab3::GetPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::GetPlan >::value();
  }
  static const char* value(const ::lab3::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::GetPlanRequest> should match 
// service_traits::DataType< ::lab3::GetPlan > 
template<>
struct DataType< ::lab3::GetPlanRequest>
{
  static const char* value()
  {
    return DataType< ::lab3::GetPlan >::value();
  }
  static const char* value(const ::lab3::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab3::GetPlanResponse> should match 
// service_traits::MD5Sum< ::lab3::GetPlan > 
template<>
struct MD5Sum< ::lab3::GetPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::GetPlan >::value();
  }
  static const char* value(const ::lab3::GetPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::GetPlanResponse> should match 
// service_traits::DataType< ::lab3::GetPlan > 
template<>
struct DataType< ::lab3::GetPlanResponse>
{
  static const char* value()
  {
    return DataType< ::lab3::GetPlan >::value();
  }
  static const char* value(const ::lab3::GetPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB3_MESSAGE_GETPLAN_H
